// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgoUu77MAp7INH9KHV1kMV5JisaU361h0',
    appId: '1:84766249348:web:54db2b6217eb4a3abb0dd1',
    messagingSenderId: '84766249348',
    projectId: 'swifty-protein-47de5',
    authDomain: 'swifty-protein-47de5.firebaseapp.com',
    storageBucket: 'swifty-protein-47de5.firebasestorage.app',
    measurementId: 'G-FXBREL9911',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6yLlbqa1Dw8NCubEfyvUuqQjZd256cFA',
    appId: '1:84766249348:android:951baaf57f9e1bfdbb0dd1',
    messagingSenderId: '84766249348',
    projectId: 'swifty-protein-47de5',
    storageBucket: 'swifty-protein-47de5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC82HQQutmfceVS9G4H_6UiTsBslDRROLk',
    appId: '1:84766249348:ios:5ebfc4dbfd963f97bb0dd1',
    messagingSenderId: '84766249348',
    projectId: 'swifty-protein-47de5',
    storageBucket: 'swifty-protein-47de5.firebasestorage.app',
    iosBundleId: 'com.example.swiftyProteins',
  );
}
